/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todo.gui;

import todo.task.model.Task;

/**
 *
 * @author huangyuhan
 */
public class AddTaskBox extends javax.swing.JPanel {

    /**
     * Creates new form AddTaskBox
     */
    public AddTaskBox() {
        initComponents();
    }
    
    public void doAdd(){
        TaskListPanel _listPanel = (TaskListPanel) this.getParent();
        _listPanel.add(generateTask());
        _listPanel.remove(this);
    }
    
    public Task generateTask(){
        Task _task;
        _task = new Task(this.taskBox1.getTextField().getText(),((TaskListPanel) this.getParent()).getTaskList());
        return _task;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        taskBox1 = new todo.gui.TaskBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/todo/gui/addIcon.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));
        add(taskBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.doAdd();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private todo.gui.TaskBox taskBox1;
    // End of variables declaration//GEN-END:variables
}
