/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package todo.gui;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import todo.task.model.Task;

/**
 *
 * @author huangyuhan
 */
public class AddTaskBox extends javax.swing.JPanel{
    private AddTaskBox _thisBox = this;
    private TaskListPanel _parent ;
    private int _lastOrder;
    

    /**
     * Creates new form AddTaskBox
     */
    public AddTaskBox() {
    }
    public AddTaskBox(TaskListPanel parent,int lastOrder){
        this._parent = parent;
        this._lastOrder = lastOrder;
        this.setBackground(new java.awt.Color(250,250,250)); 
        initComponents();       
        this.setPreferredSize(new java.awt.Dimension(TaskBox._WIDTH,TaskBox._HEIGHT/3*2));      
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(TaskBox._HEIGHT,TaskBox._HEIGHT/3*2), new java.awt.Dimension(0, 0));
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(TaskBox._WIDTH,30));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
        add(filler1);

        jTextField1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, TaskBox._HEIGHT/5*2));
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("点击以添加");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(TaskBox._HEIGHT*5,TaskBox._HEIGHT/3*2));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        add(jTextField1);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if(this.jTextField1.getText().equalsIgnoreCase("")){
            this.jTextField1.setText("点击以添加");
            this.jTextField1.setForeground(new java.awt.Color(204,204,204));
        } else{
            _parent.addTask(this.jTextField1.getText(),_lastOrder);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        this.jTextField1.setText("");
        this.jTextField1.selectAll();
        this.jTextField1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(this.jTextField1.getText().equalsIgnoreCase("")){
            this.jTextField1.setText("点击以添加");
            this.jTextField1.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
