/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this TaskBox file, choose Tools | Templates
 * and open the TaskBox in the editor.
 */
package todo.gui;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import todo.task.model.Task;

/**
 *
 * @author huangyuhan
 */
public class TaskBox extends javax.swing.JPanel implements javax.swing.ListCellRenderer{
    private Task _task;
    
    /**
     * 含参数构造方法，接受一个Task对象，将它的引用保存在TaskBox对象内部，
     * 并且将TaskBox中的文本框设置为task.title的内容.
     * 
     * @author: huangyuhan
     */
     public TaskBox(){
        super();
        initComponents();
    }
    public TaskBox(Task task){
        this();
        _task = task;
        _taskTitleField.setText(_task.getTitle());
    }
    
    public javax.swing.JTextField getTextBox(){
        return this._taskTitleField;
    }
    
    

    
    @Override
    /**
     * 实现此方法是为了实现javax.swing.ListCellRenderer接口,
     * 此方法会被jTaskList调用，其返回值是用于放在cell中显示的Component对象,
     * 其接受的参数中的value字段，是对应的TaskListModel中的对象.
     * 
     * @author: huangyuhan
     */
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        //this._taskTitleField.
        return ((TaskBox)value);
    }
    
    public javax.swing.JCheckBox getCheckBox(){
        return this.jCheckBox1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _taskTitleField = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N

        _taskTitleField.setFont(new java.awt.Font("Microsoft YaHei", 0, 22)); // NOI18N
        _taskTitleField.setText("jTextField2");
        _taskTitleField.setBorder(null);
        _taskTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _taskTitleFieldActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_taskTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(_taskTitleField)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void _taskTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__taskTitleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__taskTitleFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _taskTitleField;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
